import type { Moment } from "./types";

export const demoMoments: Moment[] = [
  {
    id: "roadtrip-bromo",
    title: "Mengejar matahari di Bromo",
    story:
      "Alarm berbunyi pukul dua pagi. Mata masih berat, tetapi kita berdua langsung bangun begitu mendengar suara jeep berhenti di depan penginapan. Udara Bromo dingin sekali dan tanganmu terus bersembunyi di saku jaketku.\n\nKita sampai tepat ketika garis jingga mulai muncul. Tidak ada yang banyak bicara. Kita hanya berdiri berdempetan, memegang gelas cokelat panas, lalu menyaksikan kabut perlahan membuka pemandangan gunung. Rasanya seperti dunia sengaja berhenti sebentar untuk kita.\n\nDi perjalanan pulang kamu bilang ini pagi paling cantik yang pernah kamu lihat. Kalimat sederhana itu jadi bagian favoritku dari seluruh perjalanan.",
    date: "2026-06-28",
    lat: -7.9425,
    lng: 112.953,
    locationName: "Bromo, Jawa Timur",
    media: [
      {
        id: "demo-mountain",
        type: "image",
        src: "/demo/mountain.jpg",
        alt: "Pemandangan pegunungan saat matahari terbit",
      },
      {
        id: "demo-road",
        type: "image",
        src: "/demo/bromo.jpg",
        alt: "Jalan panjang di antara tebing merah",
      },
      {
        id: "demo-video-sunset",
        type: "video",
        src: "/demo/sunset-memory.mp4",
        poster: "/demo/mountain.jpg",
        alt: "Video pendek perjalanan berdua",
      },
    ],
    coverPhotoId: "demo-mountain",
    collection: "Perjalanan",
    tags: ["Berdua", "Petualangan", "Sunrise"],
    mood: "Takjub",
    favorite: true,
    authorId: "member-akbar",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2026-06-28T23:10:00.000Z",
    updatedAt: "2026-06-29T01:00:00.000Z",
    deletedAt: "",
  },
  {
    id: "senja-losari",
    title: "Sore yang tidak ingin kami akhiri",
    story:
      "Rencananya cuma jalan sebentar mencari angin. Ternyata kita berhenti di tepi Losari sampai matahari benar-benar hilang.\n\nKamu memesan pisang epe tiga porsi dan bersikeras itu masih wajar. Aku tidak protes, karena sibuk memperhatikan caramu tertawa setiap kali ada anak kecil lewat mengejar burung.\n\nLangitnya berubah oranye, lalu ungu, lalu gelap. Kita masih di sana, membicarakan hal-hal kecil yang tidak penting sama sekali, dan justru itu yang paling ingin kuingat.",
    date: "2026-03-21",
    lat: -5.1417,
    lng: 119.4088,
    locationName: "Pantai Losari, Makassar",
    media: [
      {
        id: "demo-beach",
        type: "image",
        src: "/demo/beach.jpg",
        alt: "Menikmati matahari terbenam berdua",
      },
      {
        id: "demo-together",
        type: "image",
        src: "/demo/together.jpg",
        alt: "Dua orang duduk bersebelahan menghadap laut",
      },
    ],
    coverPhotoId: "demo-beach",
    collection: "Cerita Sehari-hari",
    tags: ["Senja", "Kuliner", "Berdua"],
    mood: "Damai",
    favorite: true,
    authorId: "member-aulia",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2026-03-21T12:20:00.000Z",
    updatedAt: "2026-03-22T02:00:00.000Z",
    deletedAt: "",
  },
  {
    id: "malam-ulang-tahun",
    title: "Kejutan yang hampir gagal",
    story:
      "Kue itu sempat miring di jalan dan lilinnya patah satu. Aku menahan napas sepanjang perjalanan pulang.\n\nBegitu lampu dimatikan dan kamu membuka pintu, semuanya tidak penting lagi. Kamu diam beberapa detik, lalu langsung menutup wajah dengan kedua tangan.\n\nKita makan kue itu jam sebelas malam di lantai, tanpa piring, sambil memutar lagu yang sama berulang kali.",
    date: "2026-05-03",
    lat: -5.1477,
    lng: 119.4327,
    locationName: "Rumah, Makassar",
    media: [
      {
        id: "demo-birthday",
        type: "image",
        src: "/demo/birthday.jpg",
        alt: "Kue ulang tahun dengan lilin menyala",
      },
      {
        id: "demo-party",
        type: "image",
        src: "/demo/party.jpg",
        alt: "Makan malam berdua dengan lampu hangat",
      },
    ],
    coverPhotoId: "demo-birthday",
    collection: "Perayaan",
    tags: ["Ulang tahun", "Kejutan"],
    mood: "Hangat",
    favorite: false,
    authorId: "member-akbar",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2026-05-03T15:30:00.000Z",
    updatedAt: "2026-05-04T01:00:00.000Z",
    deletedAt: "",
  },
  {
    id: "gowes-sore",
    title: "Rute baru yang salah belok",
    story:
      "Niatnya mencoba jalur baru, tapi kita salah belok dua kali dan berakhir di jalan kampung yang tidak ada di peta.\n\nTernyata itu bagian terbaiknya: pohon-pohon rapat, anak-anak menyapa dari pagar, dan warung es kelapa yang muncul persis ketika kaki sudah menyerah.",
    date: "2026-04-12",
    lat: -5.1622,
    lng: 119.4485,
    locationName: "Jalur sepeda, Makassar",
    media: [
      {
        id: "demo-home",
        type: "image",
        src: "/demo/home.jpg",
        alt: "Sore hari di jalan yang teduh",
      },
    ],
    coverPhotoId: "demo-home",
    collection: "Cerita Sehari-hari",
    tags: ["Sepeda", "Sore"],
    mood: "Seru",
    favorite: false,
    authorId: "member-akbar",
    peopleIds: ["member-akbar"],
    createdAt: "2026-04-12T10:00:00.000Z",
    updatedAt: "2026-04-12T10:30:00.000Z",
    deletedAt: "",
  },
  {
    id: "konser-pertama",
    title: "Konser pertama kita",
    story:
      "Antre tiga jam, berdiri di barisan tengah, dan tetap ikut menyanyi walau suara sudah habis di lagu kelima.\n\nKamu bilang tidak akan hafal liriknya. Ternyata kamu yang paling keras menyanyikan bagian akhirnya.",
    date: "2026-02-15",
    lat: -5.1355,
    lng: 119.4238,
    locationName: "Makassar",
    media: [
      {
        id: "demo-party-2",
        type: "image",
        src: "/demo/party.jpg",
        alt: "Suasana konser dengan lampu panggung",
      },
    ],
    coverPhotoId: "demo-party-2",
    collection: "Hari Istimewa",
    tags: ["Musik", "Berdua"],
    mood: "Gembira",
    favorite: true,
    authorId: "member-aulia",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2026-02-15T16:00:00.000Z",
    updatedAt: "2026-02-16T01:00:00.000Z",
    deletedAt: "",
  },
  {
    id: "dieng-berkabut",
    title: "Dieng yang tidak menampakkan diri",
    story:
      "Kabutnya tebal sekali sampai kita tidak melihat apa pun selain putih.\n\nKita tetap jalan pelan sambil tertawa, karena sudah jauh-jauh datang dan yang terlihat cuma dua meter di depan. Foto-fotonya hampir semua kosong, tapi entah kenapa justru itu yang paling sering kita bicarakan lagi.",
    date: "2026-01-18",
    lat: -7.2056,
    lng: 109.9078,
    locationName: "Dieng, Jawa Tengah",
    media: [
      {
        id: "demo-mountain-2",
        type: "image",
        src: "/demo/mountain.jpg",
        alt: "Pegunungan tertutup kabut tebal",
      },
    ],
    coverPhotoId: "demo-mountain-2",
    collection: "Perjalanan",
    tags: ["Kabut", "Perjalanan"],
    mood: "Tenang",
    favorite: false,
    authorId: "member-akbar",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2026-01-18T09:00:00.000Z",
    updatedAt: "2026-01-19T02:00:00.000Z",
    deletedAt: "",
  },
  {
    id: "piknik-lama-terhapus",
    title: "Piknik singkat yang terhapus",
    story:
      "Momen ini sengaja berada di tempat sampah untuk menunjukkan bahwa cerita yang terhapus masih bisa dipulihkan kapan saja dari halaman Arsip.",
    date: "2025-12-07",
    lat: -5.1502,
    lng: 119.4321,
    locationName: "Taman kota, Makassar",
    media: [
      {
        id: "demo-together-2",
        type: "image",
        src: "/demo/together.jpg",
        alt: "Piknik sederhana di ruang terbuka",
      },
    ],
    coverPhotoId: "demo-together-2",
    collection: "Cerita Sehari-hari",
    tags: ["Piknik"],
    mood: "Santai",
    favorite: false,
    authorId: "member-aulia",
    peopleIds: ["member-akbar", "member-aulia"],
    createdAt: "2025-12-07T08:00:00.000Z",
    updatedAt: "2026-01-02T04:00:00.000Z",
    deletedAt: "2026-01-02T04:00:00.000Z",
  },
];
