import type { Plan } from "./types";

export const demoPlans = [
  {
    id: "plan-road-trip-toraja",
    title: "Road trip keluarga ke Toraja",
    description:
      "Perjalanan darat empat hari untuk mengenalkan anak-anak pada kampung halaman dan mengumpulkan cerita keluarga dari Nenek.",
    category: "Perjalanan",
    status: "planning",
    priority: "high",
    targetDate: "2026-09-18",
    locationName: "Tana Toraja, Sulawesi Selatan",
    lat: -3.0753,
    lng: 119.7426,
    estimatedBudget: 8500000,
    savedAmount: 4200000,
    participants: ["Ayah", "Ibu", "Alya", "Raka"],
    checklist: [
      { id: "toraja-route", label: "Susun rute dan tempat singgah", done: true },
      { id: "toraja-stay", label: "Pesan penginapan keluarga", done: true },
      { id: "toraja-car", label: "Servis mobil sebelum berangkat", done: false },
      { id: "toraja-story", label: "Siapkan daftar cerita untuk Nenek", done: false },
    ],
    notes:
      "Bawa tripod kecil dan perekam suara. Prioritaskan waktu santai bersama keluarga, bukan mengejar terlalu banyak destinasi.",
    createdAt: "2026-06-28T08:15:00.000Z",
    updatedAt: "2026-07-20T11:30:00.000Z",
  },
  {
    id: "plan-anniversary-picnic",
    title: "Piknik ulang tahun pernikahan Ayah & Ibu",
    description:
      "Piknik kejutan sederhana dengan makanan favorit, album foto lama, dan sesi foto keluarga saat matahari sore.",
    category: "Perayaan",
    status: "ready",
    priority: "high",
    targetDate: "2026-08-16",
    locationName: "Kebun Raya Bogor",
    lat: -6.5976,
    lng: 106.7996,
    estimatedBudget: 1500000,
    savedAmount: 1500000,
    participants: ["Ayah", "Ibu", "Alya", "Raka", "Nenek"],
    checklist: [
      { id: "picnic-ticket", label: "Beli tiket masuk", done: true },
      { id: "picnic-food", label: "Pesan nasi kuning dan kue", done: true },
      { id: "picnic-album", label: "Pilih 20 foto lama untuk album", done: true },
      { id: "picnic-weather", label: "Cek prakiraan cuaca H-2", done: false },
    ],
    notes: "Datang pukul 15.00. Minta Nenek membawa surat lama Ayah dan Ibu.",
    createdAt: "2026-07-02T04:40:00.000Z",
    updatedAt: "2026-07-21T09:10:00.000Z",
  },
  {
    id: "plan-umrah-family-2027",
    title: "Umrah keluarga 2027",
    description:
      "Wishlist perjalanan ibadah keluarga sekaligus kesempatan membuat jurnal perjalanan yang bisa diwariskan kepada anak-anak.",
    category: "Keluarga",
    status: "wishlist",
    priority: "medium",
    targetDate: "2027-01-10",
    locationName: "Makkah & Madinah, Arab Saudi",
    lat: null,
    lng: null,
    estimatedBudget: 85000000,
    savedAmount: 28000000,
    participants: ["Ayah", "Ibu", "Alya", "Raka"],
    checklist: [
      { id: "umrah-passport", label: "Periksa masa berlaku paspor", done: true },
      { id: "umrah-agent", label: "Bandingkan tiga biro perjalanan", done: false },
      { id: "umrah-health", label: "Siapkan pemeriksaan kesehatan", done: false },
      { id: "umrah-saving", label: "Buat target tabungan bulanan", done: true },
    ],
    notes: "Target menabung Rp7.000.000 per bulan mulai Agustus 2026.",
    createdAt: "2026-05-12T12:20:00.000Z",
    updatedAt: "2026-07-18T06:45:00.000Z",
  },
  {
    id: "plan-family-album-2025",
    title: "Cetak album keluarga 2025",
    description:
      "Mengubah foto-foto terbaik tahun lalu menjadi album fisik lengkap dengan caption pendek dari setiap anggota keluarga.",
    category: "Proyek",
    status: "planning",
    priority: "low",
    targetDate: "",
    locationName: "Dikerjakan di rumah",
    lat: null,
    lng: null,
    estimatedBudget: 2500000,
    savedAmount: 500000,
    participants: ["Ibu", "Alya"],
    checklist: [
      { id: "album-select", label: "Kurasi 120 foto", done: false },
      { id: "album-caption", label: "Minta caption dari keluarga", done: false },
      { id: "album-vendor", label: "Pilih vendor cetak album", done: true },
    ],
    notes: "Gunakan satu halaman khusus untuk resep dan tulisan tangan Nenek.",
    createdAt: "2026-07-08T03:00:00.000Z",
    updatedAt: "2026-07-17T13:25:00.000Z",
  },
  {
    id: "plan-cooking-class",
    title: "Kelas memasak masakan Bugis bersama",
    description:
      "Belajar membuat barongko dan buras bersama Tante Mira lalu mendokumentasikan resep keluarga langkah demi langkah.",
    category: "Kuliner",
    status: "completed",
    priority: "medium",
    targetDate: "2026-06-12",
    locationName: "Rumah Tante Mira, Makassar",
    lat: -5.1477,
    lng: 119.4327,
    estimatedBudget: 900000,
    savedAmount: 900000,
    participants: ["Ibu", "Alya", "Tante Mira"],
    checklist: [
      { id: "cook-ingredients", label: "Belanja bahan bersama", done: true },
      { id: "cook-recorder", label: "Siapkan kamera dan perekam", done: true },
      { id: "cook-recipe", label: "Tulis ulang resep Tante Mira", done: true },
    ],
    notes: "Selesai. Foto dan video sudah siap diubah menjadi momen keluarga.",
    createdAt: "2026-05-25T10:00:00.000Z",
    updatedAt: "2026-06-12T15:40:00.000Z",
  },
] satisfies Plan[];
