import type { Plan } from "./types";

export const demoPlans = [
  {
    id: "plan-road-trip-toraja",
    title: "Road trip berdua ke Toraja",
    description:
      "Perjalanan darat empat hari menyusuri jalur pegunungan, berhenti di mana saja yang menarik, tanpa jadwal ketat.",
    category: "Perjalanan",
    status: "planning",
    priority: "high",
    targetDate: "2026-09-18",
    locationName: "Tana Toraja, Sulawesi Selatan",
    lat: -3.0753,
    lng: 119.7426,
    estimatedBudget: 8500000,
    savedAmount: 4200000,
    participants: [],
    checklist: [
      { id: "toraja-route", label: "Susun rute dan tempat singgah", done: true },
      { id: "toraja-stay", label: "Pesan penginapan", done: true },
      { id: "toraja-car", label: "Servis mobil sebelum berangkat", done: false },
      { id: "toraja-playlist", label: "Siapkan playlist perjalanan", done: false },
    ],
    notes:
      "Bawa tripod kecil. Prioritaskan waktu santai berdua, bukan mengejar terlalu banyak destinasi.",
    createdAt: "2026-06-28T08:15:00.000Z",
    updatedAt: "2026-07-20T11:30:00.000Z",
  },
  {
    id: "plan-anniversary-picnic",
    title: "Piknik anniversary di bukit",
    description:
      "Piknik sederhana dengan makanan favorit, album foto lama, dan sesi foto saat matahari sore.",
    category: "Perayaan",
    status: "ready",
    priority: "high",
    targetDate: "2026-08-30",
    locationName: "Bukit Bulusaraung, Maros",
    lat: -4.9214,
    lng: 119.6553,
    estimatedBudget: 750000,
    savedAmount: 750000,
    participants: [],
    checklist: [
      { id: "picnic-basket", label: "Siapkan keranjang dan alas", done: true },
      { id: "picnic-food", label: "Masak bekal favorit", done: true },
      { id: "picnic-photo", label: "Cetak beberapa foto lama", done: true },
    ],
    notes: "Berangkat sebelum jam tiga supaya tidak kehabisan cahaya sore.",
    createdAt: "2026-05-02T09:00:00.000Z",
    updatedAt: "2026-08-10T06:40:00.000Z",
  },
  {
    id: "plan-masak-bareng",
    title: "Belajar masak satu resep tiap bulan",
    description:
      "Satu resep baru setiap bulan, dimasak berdua, lalu dicatat hasilnya di album.",
    category: "Kencan",
    status: "wishlist",
    priority: "medium",
    targetDate: "",
    locationName: "",
    lat: null,
    lng: null,
    estimatedBudget: 0,
    savedAmount: 0,
    participants: [],
    checklist: [
      { id: "masak-list", label: "Buat daftar resep yang ingin dicoba", done: false },
      { id: "masak-alat", label: "Lengkapi alat yang belum ada", done: false },
    ],
    notes: "Mulai dari yang gampang dulu supaya tidak kapok.",
    createdAt: "2026-04-18T02:00:00.000Z",
    updatedAt: "2026-04-18T02:00:00.000Z",
  },
  {
    id: "plan-album-cetak",
    title: "Cetak album 2025",
    description:
      "Mengubah foto-foto terbaik tahun lalu menjadi album fisik lengkap dengan caption pendek dari kita berdua.",
    category: "Proyek",
    status: "completed",
    priority: "medium",
    targetDate: "2026-02-14",
    locationName: "",
    lat: null,
    lng: null,
    estimatedBudget: 900000,
    savedAmount: 900000,
    participants: [],
    checklist: [
      { id: "album-pilih", label: "Pilih 60 foto terbaik", done: true },
      { id: "album-caption", label: "Tulis caption tiap halaman", done: true },
      { id: "album-cetak", label: "Pesan cetak dan jilid", done: true },
    ],
    notes: "Ternyata bagian tersulitnya memilih, bukan mencetak.",
    createdAt: "2025-12-20T04:00:00.000Z",
    updatedAt: "2026-02-14T08:00:00.000Z",
  },
  {
    id: "plan-kuliner-malam",
    title: "Coba sepuluh tempat makan malam baru",
    description:
      "Daftar tempat makan yang sering dibicarakan tapi belum pernah didatangi.",
    category: "Kuliner",
    status: "planning",
    priority: "low",
    targetDate: "2026-12-31",
    locationName: "Makassar",
    lat: -5.1477,
    lng: 119.4327,
    estimatedBudget: 1500000,
    savedAmount: 450000,
    participants: [],
    checklist: [
      { id: "kuliner-daftar", label: "Kumpulkan sepuluh nama tempat", done: true },
      { id: "kuliner-jadwal", label: "Atur satu tempat tiap bulan", done: false },
      { id: "kuliner-catat", label: "Catat yang paling enak", done: false },
    ],
    notes: "Simpan struknya, lumayan jadi kenang-kenangan.",
    createdAt: "2026-01-05T05:30:00.000Z",
    updatedAt: "2026-07-01T09:15:00.000Z",
  },
] satisfies Plan[];
