import type { Moment } from "./types";

export const demoMoments: Moment[] = [
  {
    id: "roadtrip-bromo",
    title: "Mengejar matahari di Bromo",
    story:
      "Alarm berbunyi pukul dua pagi. Mata masih berat, tetapi semua langsung bangun ketika mendengar suara jeep berhenti di depan penginapan. Udara Bromo dingin sekali dan tangan kecil Nara terus bersembunyi di saku jaket Ayah.\n\nKami sampai tepat ketika garis jingga mulai muncul. Tidak ada yang banyak bicara. Kami hanya berdiri berdempetan, memegang gelas cokelat panas, lalu menyaksikan kabut perlahan membuka pemandangan gunung. Rasanya seperti dunia sengaja berhenti sebentar untuk kami.\n\nDi perjalanan pulang, Nara bilang ini adalah pagi paling cantik yang pernah ia lihat. Kalimat sederhana itu jadi bagian favorit dari seluruh perjalanan.",
    date: "2026-06-28",
    lat: -7.9425,
    lng: 112.953,
    locationName: "Bromo, Jawa Timur",
    media: [
      {
        id: "demo-mountain",
        type: "image",
        src: "/demo/mountain.jpg",
        alt: "Pemandangan pegunungan saat matahari terbit",
      },
      {
        id: "demo-road",
        type: "image",
        src: "/demo/bromo.jpg",
        alt: "Jalan panjang di antara tebing merah",
      },
      {
        id: "demo-video-sunset",
        type: "video",
        src: "/demo/sunset-memory.mp4",
        poster: "/demo/mountain.jpg",
        alt: "Video pendek perjalanan keluarga",
      },
    ],
    coverPhotoId: "demo-mountain",
    collection: "Perjalanan",
    tags: ["Keluarga", "Petualangan", "Sunrise"],
    mood: "Takjub",
    favorite: true,
    authorId: "member-akbar",
    peopleIds: ["member-akbar", "member-aulia", "member-nara"],
    createdAt: "2026-06-29T09:21:00.000Z",
  },
  {
    id: "liburan-pantai",
    title: "Sore yang tidak ingin kami akhiri",
    story:
      "Tidak ada agenda besar hari itu. Hanya tikar, bekal dari Ibu, dan satu kantong penuh kerang yang dikumpulkan anak-anak. Menjelang senja, semua berdiri menghadap laut dan tanpa direncanakan saling bergandengan tangan.\n\nFoto ini mengingatkan kami bahwa momen terbaik sering datang saat tidak sedang dicari.",
    date: "2026-05-17",
    lat: -8.4095,
    lng: 115.1889,
    locationName: "Pantai Sanur, Bali",
    media: [
      {
        id: "demo-family-beach",
        type: "image",
        src: "/demo/home.jpg",
        alt: "Keluarga menikmati matahari terbenam di pantai",
      },
      {
        id: "demo-friends-sunset",
        type: "image",
        src: "/demo/together.jpg",
        alt: "Teman-teman menikmati senja bersama",
      },
    ],
    coverPhotoId: "demo-family-beach",
    collection: "Liburan Keluarga",
    tags: ["Keluarga", "Pantai", "Bali"],
    mood: "Tenang",
    favorite: true,
    authorId: "member-aulia",
    peopleIds: [
      "member-akbar",
      "member-aulia",
      "member-nara",
      "member-dimas",
      "member-salma",
    ],
    createdAt: "2026-05-18T10:12:00.000Z",
  },
  {
    id: "ulang-tahun-ibu",
    title: "Enam puluh tahun cerita Ibu",
    story:
      "Kami sengaja datang satu per satu supaya Ibu tidak curiga. Ketika lampu ruang makan dinyalakan, wajah kagetnya langsung berubah jadi tawa. Malam itu kami tidak hanya merayakan ulang tahun, tetapi juga mendengarkan lagi cerita-cerita masa kecil yang selalu berhasil membuat meja makan ramai.",
    date: "2026-04-09",
    lat: -6.9175,
    lng: 107.6191,
    locationName: "Bandung, Jawa Barat",
    media: [
      {
        id: "demo-birthday",
        type: "image",
        src: "/demo/birthday.jpg",
        alt: "Makan malam keluarga dengan lampu hangat",
      },
    ],
    coverPhotoId: "demo-birthday",
    collection: "Perayaan",
    tags: ["Ulang tahun", "Ibu", "Keluarga"],
    mood: "Hangat",
    favorite: false,
    authorId: "member-dimas",
    peopleIds: [
      "member-akbar",
      "member-aulia",
      "member-dimas",
      "member-salma",
    ],
    createdAt: "2026-04-10T03:45:00.000Z",
  },
  {
    id: "gowes-sore",
    title: "Gowes dadakan sebelum hujan",
    story:
      "Rencana awalnya hanya membeli es krim di ujung jalan. Entah bagaimana, kami terus mengayuh sampai ke lapangan kota. Langit mulai gelap, angin makin kencang, dan kami pulang sambil berlomba dengan rintik pertama.",
    date: "2026-02-21",
    lat: -7.7956,
    lng: 110.3695,
    locationName: "Yogyakarta",
    media: [
      {
        id: "demo-bikes",
        type: "image",
        src: "/demo/family.jpg",
        alt: "Dua orang bersepeda saat matahari terbenam",
      },
    ],
    coverPhotoId: "demo-bikes",
    collection: "Cerita Sehari-hari",
    tags: ["Sore", "Sepeda", "Spontan"],
    mood: "Gembira",
    favorite: false,
    authorId: "member-akbar",
    peopleIds: ["member-akbar", "member-aulia", "member-nara"],
    createdAt: "2026-02-21T15:40:00.000Z",
  },
  {
    id: "konser-pertama",
    title: "Konser pertama bersama Kakak",
    story:
      "Suara musiknya keras, kaki pegal, dan sinyal ponsel hilang total. Tetapi ketika lagu favorit kami dimainkan dan seluruh arena ikut menyanyi, semua terasa sepadan. Confetti di akhir acara masih terselip di dompet sampai sekarang.",
    date: "2025-12-14",
    lat: -6.3024,
    lng: 106.8951,
    locationName: "Jakarta",
    media: [
      {
        id: "demo-party",
        type: "image",
        src: "/demo/party.jpg",
        alt: "Confetti memenuhi arena konser",
      },
    ],
    coverPhotoId: "demo-party",
    collection: "Hari Istimewa",
    tags: ["Musik", "Kakak", "Pertama kali"],
    mood: "Seru",
    favorite: true,
    authorId: "member-dimas",
    peopleIds: ["member-dimas", "member-aulia"],
    createdAt: "2025-12-15T07:00:00.000Z",
  },
  {
    id: "dieng-berkabut",
    title: "Tersesat kecil di negeri kabut",
    story:
      "Jalur yang kami pilih ternyata lebih panjang dari perkiraan. Alih-alih panik, kami berhenti, membuka bekal, dan menikmati pegunungan berlapis yang muncul di sela kabut. Kadang tersesat sedikit justru memberi sudut pandang terbaik.",
    date: "2025-08-03",
    lat: -7.2031,
    lng: 109.9184,
    locationName: "Dieng, Jawa Tengah",
    media: [
      {
        id: "demo-dieng",
        type: "image",
        src: "/demo/beach.jpg",
        alt: "Pegunungan berlapis tertutup kabut",
      },
    ],
    coverPhotoId: "demo-dieng",
    collection: "Perjalanan",
    tags: ["Gunung", "Kabut", "Jalan-jalan"],
    mood: "Damai",
    favorite: false,
    authorId: "member-akbar",
    peopleIds: [
      "member-akbar",
      "member-aulia",
      "member-nara",
      "member-dimas",
    ],
    createdAt: "2025-08-04T04:16:00.000Z",
  },
  {
    id: "piknik-lama-terhapus",
    title: "Piknik kecil yang tersimpan dua kali",
    story:
      "Salinan ini dipindahkan ke tempat sampah setelah kami menemukan versi cerita yang lebih lengkap. Momen tetap disimpan sementara agar fitur pemulihan bisa dicoba tanpa kehilangan apa pun.",
    date: "2025-06-08",
    lat: -6.8915,
    lng: 107.6107,
    locationName: "Taman Hutan Raya, Bandung",
    media: [
      {
        id: "demo-piknik-trash",
        type: "image",
        src: "/demo/family.jpg",
        alt: "Piknik keluarga di ruang terbuka",
      },
    ],
    coverPhotoId: "demo-piknik-trash",
    collection: "Cerita Sehari-hari",
    tags: ["Piknik", "Arsip", "Duplikat"],
    mood: "Hangat",
    favorite: false,
    authorId: "member-aulia",
    peopleIds: ["member-akbar", "member-aulia", "member-nara"],
    createdAt: "2025-06-09T07:20:00.000Z",
    updatedAt: "2026-07-18T03:10:00.000Z",
    deletedAt: "2026-07-18T03:10:00.000Z",
  },
];
